-- ============================================================
-- MES 安全环保检测(SET)模块 波次2(P1) 12 表 DDL
-- 生成日期：2026-09-02
-- 目标库：ruoyi-vue-pro（多租户，DDL 统一带 tenant_id 公共列）
-- 说明：枚举/状态存字符串码(PASS/FAIL、ACTIVE、IOT_AUTO/MANUAL…)，JSON 配置存 varchar 文本
-- 幂等：CREATE TABLE IF NOT EXISTS
-- ============================================================

-- 1) 噪声检测记录 SET-S-004
CREATE TABLE IF NOT EXISTS `mes_set_noise_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 NOISE-YYYYMMDD-NNN',
  `plan_id` bigint DEFAULT NULL COMMENT '关联检测计划编号',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号',
  `operation_id` bigint DEFAULT NULL COMMENT '关联工序编号',
  `device_id` bigint DEFAULT NULL COMMENT '关联设备编号',
  `emp_id` bigint DEFAULT NULL COMMENT '关联人员编号(个体剂量计佩戴人)',
  `source_type` varchar(16) NOT NULL COMMENT '监测类型：STATIONARY(固定式声级计)/PERSONAL(个体剂量计)',
  `location` varchar(200) DEFAULT '' COMMENT '检测位置/区域',
  `collection_mode` varchar(16) DEFAULT 'MANUAL' COMMENT '采集方式：IOT_AUTO/MANUAL',
  `lex8h` decimal(10,3) DEFAULT NULL COMMENT '8小时等效声级 dB(A)',
  `lpeak` decimal(10,3) DEFAULT NULL COMMENT '峰值声级 dB(C)',
  `limit_lex8h` decimal(10,3) DEFAULT NULL COMMENT '限值 dB(A)≤85',
  `limit_lpeak` decimal(10,3) DEFAULT NULL COMMENT '限值 dB(C)≤140',
  `spectrum` varchar(1000) DEFAULT NULL COMMENT '频谱分析(倍频程，JSON文本)',
  `standard_id` bigint DEFAULT NULL COMMENT '关联检测标准编号',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `instrument_no` varchar(64) DEFAULT '' COMMENT '检测仪器编号',
  `inspector` varchar(64) DEFAULT '' COMMENT '检测人',
  `inspect_time` datetime NOT NULL COMMENT '检测时间',
  `photo_urls` varchar(2000) DEFAULT NULL COMMENT '检测照片URL(逗号分隔)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-噪声检测记录';

-- 2) 粉尘浓度检测记录 SET-S-005
CREATE TABLE IF NOT EXISTS `mes_set_dust_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 DUST-YYYYMMDD-NNN',
  `plan_id` bigint DEFAULT NULL COMMENT '关联检测计划编号',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号',
  `operation_id` bigint DEFAULT NULL COMMENT '关联工序编号',
  `device_id` bigint DEFAULT NULL COMMENT '关联设备编号(除尘/产尘设备)',
  `location` varchar(200) DEFAULT '' COMMENT '检测位置/作业区域',
  `dust_type` varchar(16) NOT NULL COMMENT '检测参数：TOTAL_DUST/RESPIRABLE_DUST/SIO2',
  `concentration` decimal(10,3) DEFAULT NULL COMMENT '检测浓度/含量',
  `sio2_content` decimal(5,2) DEFAULT NULL COMMENT '游离SiO2含量%(总尘且需矽尘分级时)',
  `unit` varchar(16) DEFAULT '' COMMENT '单位 mg/m3/%',
  `limit_value` decimal(10,3) DEFAULT NULL COMMENT '限值',
  `ref_standard` varchar(100) DEFAULT '' COMMENT '引用国标',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `collection_mode` varchar(16) DEFAULT 'MANUAL' COMMENT '采集方式：IOT_AUTO/MANUAL',
  `instrument_no` varchar(64) DEFAULT '' COMMENT '检测仪器编号',
  `inspector` varchar(64) DEFAULT '' COMMENT '检测人',
  `inspect_time` datetime NOT NULL COMMENT '检测时间',
  `photo_urls` varchar(2000) DEFAULT NULL COMMENT '检测照片URL(逗号分隔)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-粉尘浓度检测记录';

-- 3) 电气安全检测记录 SET-S-007
CREATE TABLE IF NOT EXISTS `mes_set_electrical_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 ELEC-YYYYMMDD-NNN',
  `plan_id` bigint DEFAULT NULL COMMENT '关联检测计划编号',
  `device_id` bigint NOT NULL COMMENT '关联设备/配电设施编号',
  `location` varchar(200) DEFAULT '' COMMENT '检测位置(配电柜/线路区域)',
  `check_item` varchar(32) NOT NULL COMMENT '检测项目：INSULATION_RESISTANCE/GROUND_RESISTANCE/LEAKAGE_ACTION_CURRENT/LEAKAGE_ACTION_TIME/WITHSTAND_VOLTAGE',
  `measured_value` decimal(12,3) DEFAULT NULL COMMENT '实测值',
  `unit` varchar(16) DEFAULT '' COMMENT '单位 MΩ/Ω/mA/ms/V',
  `limit_value` decimal(12,3) DEFAULT NULL COMMENT '标准限值',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `instrument_no` varchar(64) DEFAULT '' COMMENT '检测仪器编号',
  `instrument_calib_ok` tinyint(1) DEFAULT NULL COMMENT '仪器校准状态快照：1已校准/0未校准',
  `inspector` varchar(64) DEFAULT '' COMMENT '检测人',
  `inspect_time` datetime NOT NULL COMMENT '检测时间',
  `photo_urls` varchar(2000) DEFAULT NULL COMMENT '检测照片URL(逗号分隔)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-电气安全检测记录';

-- 4) 压力容器检测记录 SET-S-008
CREATE TABLE IF NOT EXISTS `mes_set_pressure_vessel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '检验记录/报告编号 PV-YYYY-NNN',
  `plan_id` bigint DEFAULT NULL COMMENT '关联检测计划编号',
  `device_id` bigint NOT NULL COMMENT '关联设备编号(特种设备台账)',
  `vessel_reg_no` varchar(64) DEFAULT '' COMMENT '压力容器使用登记证号(特种设备注册代码)',
  `wall_thickness` decimal(8,3) DEFAULT NULL COMMENT '壁厚测定最小壁厚 mm',
  `ndt_methods` varchar(64) DEFAULT '' COMMENT '无损检测方法：UT/RT/MT/PT(多选逗号分隔)',
  `ndt_results` varchar(1000) DEFAULT NULL COMMENT '无损检测结果JSON文本如{UT:PASS,MT:PASS}',
  `safety_valve_ok` tinyint(1) DEFAULT NULL COMMENT '安全阀校验合格：1是/0否',
  `pressure_test_value` decimal(10,3) DEFAULT NULL COMMENT '耐压试验压力 MPa',
  `pressure_test_result` varchar(8) DEFAULT NULL COMMENT '耐压试验结果 PASS/FAIL',
  `process_pressure` decimal(10,3) DEFAULT NULL COMMENT '工艺允许压力 MPa',
  `result` varchar(8) DEFAULT NULL COMMENT '综合结论 PASS/FAIL',
  `inspect_org` varchar(200) NOT NULL COMMENT '检验机构(需资质)',
  `next_inspect_date` date NOT NULL COMMENT '下次检验日期',
  `report_file_url` varchar(500) DEFAULT '' COMMENT '检验报告文件URL',
  `inspector` varchar(64) DEFAULT '' COMMENT '检验人',
  `inspect_time` datetime NOT NULL COMMENT '检验时间',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-压力容器检测记录';

-- 5) PPE防护检查记录 SET-S-012
CREATE TABLE IF NOT EXISTS `mes_set_ppe_check` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 PPE-YYYYMMDD-NNN',
  `emp_id` bigint NOT NULL COMMENT '关联人员编号(佩戴校验对象)',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号',
  `operation_id` bigint DEFAULT NULL COMMENT '关联工序编号',
  `ppe_type` varchar(32) NOT NULL COMMENT 'PPE类别：HELMET/GOGGLES/RESPIRATOR/ANTISTATIC_CLOTHING/EARPLUGS/GLOVES/SAFETY_SHOES等',
  `check_mode` varchar(16) DEFAULT 'MANUAL' COMMENT '检查方式：AI_VISION/MANUAL',
  `wearing_ok` tinyint(1) DEFAULT NULL COMMENT '佩戴完整性：1是/0否',
  `grade_match_ok` tinyint(1) DEFAULT NULL COMMENT '防护等级匹配性：1是/0否',
  `valid_ok` tinyint(1) DEFAULT NULL COMMENT '有效期/损坏检查：1是/0否',
  `expiry_date` date DEFAULT NULL COMMENT 'PPE到期日期',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `block_flag` tinyint(1) DEFAULT NULL COMMENT '是否阻断开工(FAIL时=1)',
  `device_no` varchar(64) DEFAULT '' COMMENT 'AI识别设备编号',
  `checker_name` varchar(64) DEFAULT '' COMMENT '检查人(人工检查时)',
  `check_time` datetime NOT NULL COMMENT '检查时间',
  `photo_urls` varchar(2000) DEFAULT NULL COMMENT '检查照片/AI抓拍URL(逗号分隔)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-PPE防护检查记录';

-- 6) 排放口管理 SET-E-001
CREATE TABLE IF NOT EXISTS `mes_set_emission_outlet` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `outlet_code` varchar(64) NOT NULL COMMENT '排放口编号(如 DA001/DW001)',
  `outlet_name` varchar(200) NOT NULL COMMENT '排放口名称',
  `outlet_type` varchar(16) NOT NULL COMMENT '排放类型：GAS/WASTEWATER/NOISE',
  `pollutant_codes` varchar(1000) DEFAULT NULL COMMENT '主要污染物列表(JSON/CSV文本)',
  `location` varchar(200) DEFAULT '' COMMENT '位置描述',
  `longitude` decimal(10,6) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,6) DEFAULT NULL COMMENT '纬度',
  `stack_height` decimal(8,2) DEFAULT NULL COMMENT '排气筒高度 m',
  `monitor_method` varchar(16) DEFAULT NULL COMMENT '在线监测方式：CEMS/MANUAL/NONE',
  `permit_no` varchar(64) DEFAULT '' COMMENT '关联排污许可证号',
  `permit_limits` varchar(4000) DEFAULT NULL COMMENT '许可排放限值JSON文本',
  `is_key_outlet` tinyint(1) DEFAULT NULL COMMENT '是否重点/国控排放口：1是/0否',
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outlet_code` (`outlet_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-排放口';

-- 7) 废气排放检测记录 SET-E-002
CREATE TABLE IF NOT EXISTS `mes_set_exhaust_gas` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 EXGAS-YYYYMMDD-NNN',
  `outlet_id` bigint NOT NULL COMMENT '关联排放口编号',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号',
  `pollutant_code` varchar(32) NOT NULL COMMENT '污染物：SO2/NOX/PM/VOCs/HCL/HF等',
  `concentration` decimal(12,3) DEFAULT NULL COMMENT '排放浓度 mg/m3',
  `unit` varchar(16) DEFAULT '' COMMENT '单位 mg/m3等',
  `flow_rate` decimal(12,3) DEFAULT NULL COMMENT '标态干烟气流量 m3/h',
  `emission_amount` decimal(12,3) DEFAULT NULL COMMENT '折算排放速率 kg/h',
  `limit_value` decimal(12,3) DEFAULT NULL COMMENT '限值',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `collection_mode` varchar(16) DEFAULT 'MANUAL' COMMENT '采集方式：CEMS_AUTO/MANUAL',
  `monitor_time` datetime NOT NULL COMMENT '监测时间',
  `instrument_no` varchar(64) DEFAULT '' COMMENT 'CEMS设备编号/采样仪器号',
  `inspector` varchar(64) DEFAULT '' COMMENT '监测人(手工时)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-废气排放检测记录';

-- 8) 废水排放检测记录 SET-E-003
CREATE TABLE IF NOT EXISTS `mes_set_wastewater` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 WW-YYYYMMDD-NNN',
  `outlet_id` bigint NOT NULL COMMENT '关联排放口编号',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号',
  `sample_no` varchar(64) DEFAULT '' COMMENT '实验室样品编号(手工检测时)',
  `pollutant_code` varchar(32) NOT NULL COMMENT '污染物：PH/COD/BOD5/NH3_N/TP/PETROLEUM/SS/HEAVY_METAL等',
  `concentration` decimal(12,3) DEFAULT NULL COMMENT '检测浓度 mg/L(pH无量纲)',
  `unit` varchar(16) DEFAULT '' COMMENT '单位 mg/L(pH留空)',
  `flow_rate` decimal(12,3) DEFAULT NULL COMMENT '排放流量 m3/h',
  `emission_amount` decimal(12,3) DEFAULT NULL COMMENT '排放量 kg/h',
  `limit_value` decimal(12,3) DEFAULT NULL COMMENT '限值',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `collection_mode` varchar(16) DEFAULT 'MANUAL' COMMENT '采集方式：ONLINE_AUTO/LAB_MANUAL',
  `monitor_time` datetime NOT NULL COMMENT '监测时间',
  `instrument_no` varchar(64) DEFAULT '' COMMENT '在线监测仪/化验设备编号',
  `inspector` varchar(64) DEFAULT '' COMMENT '化验员(手工时)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-废水排放检测记录';

-- 9) 碳排放核算记录 SET-E-008
CREATE TABLE IF NOT EXISTS `mes_set_carbon_emission` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `calc_no` varchar(64) NOT NULL COMMENT '核算批次号 CARBON-YYYYMM',
  `period_type` varchar(10) NOT NULL COMMENT '核算周期：DAILY/MONTHLY/YEARLY',
  `period_start` date NOT NULL COMMENT '周期开始日期',
  `period_end` date NOT NULL COMMENT '周期结束日期',
  `wo_id` bigint DEFAULT NULL COMMENT '关联工单编号(工单级碳足迹可空)',
  `source_record_id` bigint DEFAULT NULL COMMENT '关联能耗记录编号(能源台账)',
  `energy_type` varchar(20) NOT NULL COMMENT '能源类型：ELECTRICITY/NATURAL_GAS/DIESEL/STEAM',
  `consumption` decimal(15,3) DEFAULT NULL COMMENT '能源消耗量',
  `emission_factor` decimal(10,4) DEFAULT NULL COMMENT '排放因子',
  `carbon_emission` decimal(15,3) DEFAULT NULL COMMENT '碳排放量=consumption*factor',
  `unit` varchar(10) NOT NULL DEFAULT 'tCO2' COMMENT '单位 tCO2',
  `process_emission` decimal(15,3) DEFAULT NULL COMMENT '工艺排放',
  `total_emission` decimal(15,3) DEFAULT NULL COMMENT '合计',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_calc_no` (`calc_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-碳排放核算记录';

-- 10) 排污许可管理 SET-E-009
CREATE TABLE IF NOT EXISTS `mes_set_pollution_permit` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `permit_no` varchar(64) NOT NULL COMMENT '排污许可证号',
  `enterprise_name` varchar(200) NOT NULL COMMENT '排污单位名称(本企业)',
  `issuing_authority` varchar(200) DEFAULT '' COMMENT '发证机关',
  `issue_date` date DEFAULT NULL COMMENT '发证日期',
  `start_date` date DEFAULT NULL COMMENT '许可有效期起',
  `end_date` date DEFAULT NULL COMMENT '许可有效期止',
  `outlet_codes` varchar(1000) DEFAULT NULL COMMENT '绑定的排放口编号列表',
  `annual_limits` varchar(4000) DEFAULT NULL COMMENT '许可排放量JSON文本(驱动80%预警/100%报警)',
  `annual_reports` varchar(4000) DEFAULT NULL COMMENT '年度执行报告JSON文本',
  `status` varchar(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/EXPIRED/REVOKED',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_permit_no` (`permit_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-排污许可证';

-- 11) 环保检测报告 SET-E-010
CREATE TABLE IF NOT EXISTS `mes_set_env_report` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `report_no` varchar(64) NOT NULL COMMENT '报告编号 EP-YYYYMMDD-NNN',
  `report_name` varchar(200) NOT NULL COMMENT '报告名称',
  `report_type` varchar(16) NOT NULL COMMENT '报告来源：THIRD_PARTY/INTERNAL',
  `report_category` varchar(32) DEFAULT NULL COMMENT '类别：EXHAUST_GAS/WASTEWATER/NOISE/SOLID_WASTE/AMBIENT/COMPREHENSIVE等',
  `template_id` bigint DEFAULT NULL COMMENT '复用质检报告模板编号',
  `period_start` date DEFAULT NULL COMMENT '报告统计期起',
  `period_end` date DEFAULT NULL COMMENT '报告统计期止',
  `report_date` date DEFAULT NULL COMMENT '报告日期',
  `data_summary` varchar(4000) DEFAULT NULL COMMENT '检测结果摘要JSON文本',
  `file_url` varchar(500) DEFAULT '' COMMENT '报告文件URL(第三方导入PDF)',
  `sign_url` varchar(500) DEFAULT '' COMMENT '电子签名文件URL',
  `form_id` bigint DEFAULT NULL COMMENT '自定义表单配置id',
  `status` varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/APPROVED/REJECTED/ARCHIVED',
  `audit_by` varchar(64) DEFAULT '' COMMENT '审核人(终审)',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-环保检测报告';

-- 12) 职业病危害因素检测记录 SET-H-001
CREATE TABLE IF NOT EXISTS `mes_set_occupational_hazard` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `record_no` varchar(64) NOT NULL COMMENT '记录编号 OH-YYYYMMDD-NNN',
  `plan_id` bigint DEFAULT NULL COMMENT '关联检测计划编号',
  `emp_id` bigint DEFAULT NULL COMMENT '关联人员编号(个体暴露监测时；岗位检测可空)',
  `factor_category` varchar(16) NOT NULL COMMENT '因素类别：CHEMICAL/PHYSICAL/BIOLOGICAL',
  `factor_code` varchar(32) NOT NULL COMMENT '具体因素：TOXIC/DUST/NOISE/RADIATION/HEAT/VIBRATION/BIOAGENT',
  `workplace` varchar(200) NOT NULL COMMENT '检测岗位/工作场所',
  `source_ref_type` varchar(16) DEFAULT NULL COMMENT '数据来源：REUSE/ORIGINAL',
  `source_record_id` bigint DEFAULT NULL COMMENT '来源安全检测记录id(复用气体/噪声/粉尘)',
  `measured_value` decimal(12,3) DEFAULT NULL COMMENT '实测浓度/强度',
  `unit` varchar(16) DEFAULT '' COMMENT '单位 mg/m3/dB(A)/mSv/C/m-s2等',
  `limit_type` varchar(16) DEFAULT NULL COMMENT '接触限值类型：MAC/PC-TWA/PC-STEL',
  `oel_value` decimal(12,3) DEFAULT NULL COMMENT '职业接触限值',
  `ref_standard` varchar(100) DEFAULT '' COMMENT '引用国标',
  `result` varchar(8) DEFAULT NULL COMMENT '结果：PASS/FAIL',
  `inspector` varchar(64) DEFAULT '' COMMENT '检测人',
  `inspect_time` datetime NOT NULL COMMENT '检测时间',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='MES SET-职业病危害因素检测记录';
